import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const apkUrl = 'https://drive.usercontent.google.com/download?id=1PFnzcWnHuJqGBdX798iDzNKXQokmg_As&export=download&authuser=0'; // Replace with your actual APK URL

  return (
    <>
      <Head>
        <title>Mail Reader</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet"></link>
        {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGOI1aFkw7cmDA6j6gD" crossorigin="anonymous"></link> */}
      </Head>

      <div className={`container-fluid ${styles.body}`}>
        <main className={`container-fluid ${styles.main}`}>
          <h1 className={styles.head}>MAIL READER</h1>
          <p className="text-center">Click the button below to download the APK file:</p>
          <a className={styles.button} href={apkUrl} download>
            Download APK
          </a>
          <p>v0.01</p>
        </main>
      </div>
    </>
  );
}
